Feat/nota carioca xml#1
Omnis-Solucoes-Juridicas/nota-carioca-node pull request #3
Opened 2024-08-15 20:28 UTC by MarkusLima

![CancelarNota](https://github.com/user-attachments/assets/321572b0-a78f-4a72-ad7d-cedd2c0dd4e4)
![ConsultaRPS](https://github.com/user-attachments/assets/7e6264c8-a36c-4adf-9fb7-9f7bac4e716a)
![GerarNota1](https://github.com/user-attachments/assets/a778fdcd-a53d-4663-9248-0b7850cbff73)
![GerarNota2](https://github.com/user-attachments/assets/c3343671-aad1-45e0-8f38-37b4cad86581)

2024-08-16 15:27 UTC, jonathansouza1 requested changes
Revise todos os XMLs finais para ver se bate com o modelo esperado

2024-08-16 15:27 UTC, jonathansouza1 commented on lib/services/ConsultarNotaCariocaRPS.js
>          const xmlBuilder = new xml2js.Builder({ rootName: 'rootnode', xmldec: { version: '1.0', encoding: 'UTF-8' } });
Modifique a forma como é construído o XML baseado no código de construção de ConsultarNotaCarioca.

Faça a construção e tratamento do XML da mesma forma. Utilizando try catch e variável `let content`.

2024-08-16 15:27 UTC, jonathansouza1 commented on example/consultar.nota.carioca.rps.example.js
Note que o resultado ainda não está igual o esperado. Observe todas as urls nos atributos do formato esperado e todas as tags.

Formato obtido: 

```
 <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
        <soap:Body>
          <ConsultarNfsePorRpsRequest xmlns="http://notacarioca.rio.gov.br/">
            <inputXML>
              <![CDATA[
                <ConsultarNfseRpsEnvio xmlns="http://notacarioca.rio.gov.br/WSNacional/XSD/1/nfse_pcrj_v01.xsd">

  <ConsultarNfseRpsEnvio>
    <IdentificacaoRps>
      <Numero>1</Numero>
      <Serie>ABC</Serie>
      <Tipo>1</Tipo>
    </IdentificacaoRps>
    <Prestador>
      <Cnpj>12123736000136</Cnpj>
      <InscricaoMunicipal>12345678</InscricaoMunicipal>
    </Prestador>
  </ConsultarNfseRpsEnvio>
</ConsultarNfseRpsEnvio>
              ]]>
            </inputXML>
          </ConsultarNfsePorRpsRequest>
        </soap:Body>
      </soap:Envelope>
```

Formato esperado:

`<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"> <soap:Body> <ConsultarNfsePorRpsRequest xmlns="http://notacarioca.rio.gov.br/"> <inputXML> <![CDATA[ <ConsultarNfseRpsEnvio xmlns="http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd"><IdentificacaoRps><Numero>1</Numero><Serie>A</Serie><Tipo>1</Tipo></IdentificacaoRps><Prestador><Cnpj>12218427000172</Cnpj><InscricaoMunicipal>02247211</InscricaoMunicipal></Prestador></ConsultarNfseRpsEnvio> ]]> </inputXML> </ConsultarNfsePorRpsRequest> </soap:Body> </soap:Envelope>`

2024-08-16 15:27 UTC, jonathansouza1 commented on lib/services/CancelarNota.js
Modifique a forma como é construído o XML baseado no código de construção de ConsultarNotaCarioca.

Faça a construção e tratamento do XML da mesma forma. Utilizando try catch e variável let content.

2024-08-16 15:27 UTC, jonathansouza1 commented on lib/services/GerarNotaCarioca.js
Modifique a forma como é construído o XML baseado no código de construção de ConsultarNotaCarioca.

Faça a construção e tratamento do XML da mesma forma. Utilizando try catch.

2024-08-16 19:10 UTC, MarkusLima reviewed
Feito ajustes.

2024-08-19 13:10 UTC, Luis-Carlos-Moraes requested changes

2024-08-19 13:10 UTC, Luis-Carlos-Moraes commented on lib/services/CancelarNota.js
Resolver conflito 
![image](https://github.com/user-attachments/assets/1152a70b-8821-4f7d-a48d-9f223e70e263)

2024-08-19 14:53 UTC, jonathansouza1 requested changes

2024-08-19 14:53 UTC, jonathansouza1 commented on lib/services/GerarNotaCarioca.js
Correções no XML final:

- Remover bloco <RpsSubstituido>
- Bloco <Valores> está incompleto
- Bloco <Tomador> incompleto

2024-08-19 15:51 UTC, Luis-Carlos-Moraes requested changes

2024-08-19 15:51 UTC, Luis-Carlos-Moraes commented on example/cancelar.nota.carioca.example.js
![image](https://github.com/user-attachments/assets/f0df61c9-878b-4e7d-b749-f9f88c9a5d45)
 a tag <ConsultarNfseRpsEnvio> está aberta duas vezes

2024-08-20 12:52 UTC, MarkusLima reviewed
Feito ajuste

2024-08-21 12:55 UTC, Luis-Carlos-Moraes requested changes
![image](https://github.com/user-attachments/assets/254aca28-07ad-4c53-855a-517ba14aad3d)

2024-08-21 12:55 UTC, Luis-Carlos-Moraes commented on example/consultar.nota.carioca.rps.example.js
![image](https://github.com/user-attachments/assets/f0df61c9-878b-4e7d-b749-f9f88c9a5d45)
 a tag <ConsultarNfseRpsEnvio> está aberta duas vezes

2024-08-21 13:28 UTC, MarkusLima reviewed
Feito ajuste

2024-08-21 13:44 UTC, Luis-Carlos-Moraes requested changes
![image](https://github.com/user-attachments/assets/f4dacb49-b3e7-4dbb-afb4-8edb66de9504)

@MarkusLima sempre verifica com **npx eslint --fix .**  antes de finalizar o P.R.

2024-08-21 14:54 UTC, Luis-Carlos-Moraes requested changes
Organizar os atributos das entidades de acordo com a ordem especificada no exemplo, garantindo consistência e praticidade na analise da revisão final.

2024-09-30 16:05 UTC, jonathansouza1 approved these changes

2024-09-30 16:05 UTC, merged